version: '2'

services:

  php:
    image: enclaive/php-sgx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
